ALTER TABLE image MODIFY COLUMN post_id BIGINT NULL;
ALTER TABLE image DROP FOREIGN KEY FK_IMAGE_ON_POST;
ALTER TABLE image ADD CONSTRAINT FK_IMAGE_ON_POST FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE SET NULL;
